### ISSUE TITLE
Inicijalna baza podataka

### ISSUE THREAD

**Issue by Ivan-Dujmic** [fran-galic/EasyRent#1]
@fran-galic ajde ostavi ovdje komentare koje si imao na Vilimovu inicijalnu bazu

**Comment by Ivan-Dujmic** [comment]
Odlučit se za jedninu (ili množinu) za imena tablica.

User: 
password -> passwordHash?
Treba li nam homeAddress? Mislim da nema potrebe pamtit taj podataka za korisnike
Ako ce user vec imat ID onda neka im to bude key?

Rentoid:
Pratimo li na kraju age?

Working Hours:
daysOfWeek -> dayOfTheWeek/dayOfWeek

Rents:
Ima samo od kada je rent, a ne i do kada

Reviews:
Ne znam jel bi osoba trebala više puta moći ocijeniti isti auto. Ako ne onda dateTimeRented treba zamijeniti s ključem Rentoida.

Vehicle:
*timesRented je suvišno, može se izvuči kao count rentova za registraciju

VehicleCondition:
pojasni, što točno označava onDate, treba li nam ova tablica s obzirom na trenutnu arhitekturu?

Offers:
noOfReviews
*noOfReviews i rating su suvišni
Što je rating description? (generalno bi dobro došao opis svega)

Doradit channel
Možda nam treba nešto za pratit transakcije?
Popravi što se da pa možemo na sljedećem meetingu svi zajedno poradit na ovom.

**Comment by fran-galic** [comment]
Spomenuo si sve komentare koje sam zasada i ja našao pa od mene ništa.

**Comment by vilim-hrupelj** [comment]
Adresa možda nije potrebna, tho email mora bit kljuć jer pretpostavljam da user može napravit više računa tho to je za diskusiju (onda nije unique zapravo lol)
Također je pitanje ima li smisla izdvajat Usera uopće il sam radit sve posebno za Rentoide i Dealere. Mislim da je ovak bolje jer je fleksibilnije.

Što se tiće ratinga mislim da ima smisla da ista osoba može ratat isto vozilo više puta (kao što ak prođu 2 godine, auto je tehnički isti al je realno drugaćiji)

returnDateTime sam izbrisao slučajno u nekom trenutku lol

WorkingHours ću objasnit u dokumentu, malo je komplicirano, al množina mi tu ima smisla jer je takav izraz, ko zbirna imenica.

timesRented, rating, noOfRatings i ratingDescription su stvari koje možeš dohvatit od drugdje ali mislim da ima benefit da ih spremiš zasebno. Ovisno kolko se često mjenjaju right? Kolko očekujemo reviews daily, a kolko pregleda stranice daily?
Mislim da se isplati pohranit ih i updatat za svaki review, al možemo raspravit o tome.

ratingDescription je shorthand za rating tipa VERY POPULAR za rating > 9.0, to se recimo vjv isplati evaluirat on demand, al nez di da zapišem virtualne stupce.

VehicleCondition ću isto još pojasnit u opisu baze. Slično je ko s rating, služi za evidenciju povjesti stanja tak da možeš vidjet u kakvom je stanju netko dobio i ostavio vozilo.

Channel je za sad sam neki kanal za messaging, nije samo između rentoida i kuća neg može služit i za admina.
Je li potrebno evidentirat transakcije? Pretpostavio sam da će se one izvodit prek nekog drugog posrednika tipa paypal, pa nije na nama.

**Comment by vilim-hrupelj** [comment]
evo baza je complete za sad, bacite oko

**Comment by Ivan-Dujmic** [comment]
Super za inicijalnu bazu

Neke stvari koje ćemo morat još rješit kad budemo znali kako se to radi:

Location - s obzirom da koristimo karte (Google Maps ili OpenStreetMap), neznamo još koje podatke za lokacije ćemo pohranjivat pa će možda doći do promjene location tablice i time i HQAdress (btw piše se Address) atributa u dealership tablici.

Sve vezano na novčane transakcije.

VehicleCondition nije loša ideja za dodati u aplikaciju. Možemo prodiskusirati i razmisliti što sve treba zapisivati.

Chat (channel) iako se čini dobro trenutno, neznam još kako se chat izvodi.
