### ISSUE TITLE
5. poglavlje dokumentacije

### ISSUE THREAD

**Issue by Ivan-Dujmic** [fran-galic/EasyRent#19]

**Comment by karlo-brzak-fer** [comment]
![Razredi](https://github.com/user-attachments/assets/e5241e8d-efe9-4dc8-bba6-3c62e65b21b0)

**Comment by Ivan-Dujmic** [comment]
napisao si desno da su svi atributi public, jesi siguran za to?

**Comment by Ivan-Dujmic** [comment]
dodaj u 5. poglavlje ako si gotov

**Comment by karlo-brzak-fer** [comment]
Je poslat cu prije ponoci, a ako mislis da neki nije public javi al kolko znam mozemo izravno pristupit svakom atributu

**Comment by Ivan-Dujmic** [comment]
imaš pravo, na krivi način sam razmišljao o private/public
