### ISSUE TITLE
Inicijalni UML dijagrami

### ISSUE THREAD

**Issue by Ivan-Dujmic** [fran-galic/EasyRent#3]

**Comment by karlo-brzak-fer** [comment]
![Funkcionalnosti administratora](https://github.com/user-attachments/assets/8e3df361-e567-43f8-bed7-7207cef6f524)
![Funkcionalnosti automobilske kuce](https://github.com/user-attachments/assets/06f14086-5e7f-4716-afe0-a392497e8089)
![Funkcionalnosti iznajmljivaca i neprijavljenog korisnika](https://github.com/user-attachments/assets/b09f7d41-4de9-4b24-9d70-25dcd8549fcd)
![Pregled dostupnih vozila i rezervacija](https://github.com/user-attachments/assets/5efbe9e8-9fd0-44b0-a0b6-921308b26ad3)
![Registracija](https://github.com/user-attachments/assets/35412f08-11df-46d7-9310-6ed6048a20dd)

**Comment by karlo-brzak-fer** [comment]
![Funkcionalnosti administratora](https://github.com/user-attachments/assets/2dc93e19-965a-452c-8b9f-eb9d0fb2eb91)
![Funkcionalnosti automobilske kuce](https://github.com/user-attachments/assets/2a6a0311-43f7-41ed-905a-a82ba6ceaa4b)
![Funkcionalnosti iznajmljivaca i neprijavljenog korisnika](https://github.com/user-attachments/assets/02ab37a4-8202-46a0-ab8a-ff4dc4e714c5)
![Pregled dostupnih vozila i rezervacija](https://github.com/user-attachments/assets/542e99c1-3058-4d7e-b5cc-df1b9d816fa6)
![Registracija](https://github.com/user-attachments/assets/4cb36510-a087-4ddb-a6c0-2ca2ff0a16b3)

**Comment by Matija-Kukic** [comment]
Promijenjeni tu pojedini funkcijski zahtjevi za koje treba prepraviti use case-eve i dodati ih u prva dva uml dijagrama.

**Comment by karlo-brzak-fer** [comment]
![registracija](https://github.com/user-attachments/assets/216ecfcb-e90e-4810-b732-4a44608ff140)
![pretraga_i_rezervacija](https://github.com/user-attachments/assets/f3311b65-3ddf-4cf3-b1d9-a0669a29daae)
