### ISSUE TITLE
Backend postavit endpointe

### ISSUE THREAD

**Issue by Ivan-Dujmic** [fran-galic/EasyRent#6]

**Comment by Ivan-Dujmic** [comment]
Link koji si mi poslao: https://1drv.ms/w/c/10ffb9cb521608c3/ERLcOJuClqdKrG0OA89MwPsB_gax1EnIxIJCllGX1heANA?e=KAntUH
- Ovo za working hours mozda ima vise smisla da je nedjelja 0 (tak je u sql ak se ne varam)
- Mislim da si dobro cak stavio za google maps info (tak mi imamo za projekt r), ali vidjet cemo
- Ovo sto se tice da saljes kompaniju na /api/guest/home mislim da nema uopce veze s nama vec ce frontend redirectat na /home bez api
- Kako točno zamišljaš ovaj /api/login/:userId ? nije mi baš najjasnije
- (carId, model, make) za kartice bi mozda trebalo biti registration i modelId (neznam iskreno jer je Vilim zamislio da korisnici ne vide više verzija istog auta iste kompanije dok ih kompanije mogu razlikovati, ali to će se dosta igrati sa stvarima)
- S obzirom da se home za korisnika i gosta razlikuje samo u osobnim stvarima (ime prezime balance) možeš imat samo jedan endpointa za home i onda jedan endpoint za fetchanje user data (ime prezime balans i ako jos nesto treba) sto ce se moc koristit na svakoj podstranici. Sad ovo sa gledišta homea ne izgleda kao neka posebna optimizacija jer mislim da je za home čak samo potreban taj jedan get endpoint tako da i može ostat kako je, ali za druge stranice (npr listing s filtriranjem) ce biti puno getova, a user info ostaje isti, ali mislim da nije lose razdvojit i za home u slucaju nadogradivanja
- Fali u home get endpointu dobavljanje nekoliko firmi za prikazat gore
- Ako se ne varam mislim da kompanije nemaju home page neg ih redirekta na njihov profil pa im ne treba home endpoint, ali nez
- Mislim da bi admin za potvrdu registracije firme trebao imati više podataka (phone number, headquarters location jos)

**Comment by karlo-brzak-fer** [comment]
- Istina sql dow funkcija vraća 0 za nedjelju tako da bi pretraživanje bilo lakše ako tako stavimo, ali onda moram javiti Vilimu da tako čuva radno vrijeme u bazi (možda je manje pregledno nego da ima pon, uto, sri... ali lakše je za pretraživanje)
- može vidjet ćemo
- istina može ga i frontend redirectati, malo je jednostavnije
- na mail će se poslati link koji sadrži userId korisnika koji se želi registrirati, a klikom na link korisnika se šalje na login. Kada korisnik popuni podatke u loginu, form se POST-a na /api/login/:userId te backend iz linka može pročitati id korisnika i shvatiti da se radi o potvrdi registracije
- sve ćemo vidjeti kad Vilim postavi finalnu verziju, ako nešto što nam treba ne bude u bazi poslat ću mu poruku i mislim da će lako dodati
- istina biti će efikasnije tako
- dodano
- istina, ali sve ovisi o tome kako ćemo tu stranicu zvati jer to je ujedno i home i profile od kompanije
- može dodao sam
